<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        /*work but type 02
        ===================*/
        $users = [
            [
                'name' => 'Super Admin',
                'email' => 'superadmin@mail.com',
                'password' => bcrypt('password'),
                'image' => null,
                'password' => bcrypt('password'),
                'role' => 1,
                'designation' => 'Admin',
                'balance' => 100,
                'status' => 1,
                'is_read' => 1,
            ],
            // [
            //     'name' => 'Stewart Leonard',
            //     'email' => 'stewartleonard06@gmail.com',
            //     'image' => null,
            //     'password' => bcrypt('Test@12345'),
            //     'role' => 1,
            //     'designation' => 'President',
            //     'status' => 1,
            //     'is_read' => 1,
            // ],
            [
                'name' => 'Omar Farid',
                'email' => 'ofarid27@gmail.com',
                'image' => null,
                'password' => bcrypt('Test@12345'),
                'role' => 1,
                'designation' => 'Developer',
                'balance' => 100,
                'status' => 1,
                'is_read' => 1,
            ],
            [
                'name' => 'Marif Akter',
                'email' => 'marif@gmail.com',
                'image' => null,
                'password' => bcrypt('Test@12345'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 1,
            ],
            // [
            //     'name' => 'Anthony Harper',
            //     'email' => 'anthony@mail.com',
            //     'image' => 'Anthony-Harper.jpg',
            //     'password' => bcrypt('12345678'),
            //     'role' => 0,
            //     'designation' => null,
            //     'status' => 1,
            //     'is_read' => 0,
            // ],

            /*member list start here
            ===================*/

            // [
            //     'name' => 'Joseph Dennis Jr.',
            //     'email' => 'joseph@mail.com',
            //     'image' => 'Joseph-Dennis-Jr_0.JPG',
            //     'password' => bcrypt('12345678'),
            //     'role' => 0,
            //     'designation' => 'Vice President',
            //     'status' => 1,
            //     'is_read' => 0,
            // ],
            // [
            //     'name' => 'Tyrone Wiley',
            //     'email' => 'tyrone@mail.com',
            //     'image' => 'Tyrone-Wiley_0.JPG',
            //     'password' => bcrypt('12345678'),
            //     'role' => 0,
            //     'designation' => 'Recording Secretary',
            //     'status' => 1,
            //     'is_read' => 0,
            // ],
            // [
            //     'name' => 'James Smith',
            //     'email' => 'james@mail.com',
            //     'image' => 'James-Smith.jpg',
            //     'password' => bcrypt('12345678'),
            //     'role' => 0,
            //     'designation' => 'Financial Secretary',
            //     'status' => 1,
            //     'is_read' => 0,
            // ],
            // [
            //     'name' => 'Xavier Poellnitz',
            //     'email' => 'xavier@mail.com',
            //     'image' => 'Xavier-Poellnitz.jpg',
            //     'password' => bcrypt('12345678'),
            //     'role' => 0,
            //     'designation' => 'Corresponding Secretary',
            //     'status' => 1,
            //     'is_read' => 0,
            // ],
            // [
            //     'name' => 'Darren Smith',
            //     'email' => 'darren@mail.com',
            //     'image' => 'Darren-Smith.jpg',
            //     'password' => bcrypt('12345678'),
            //     'role' => 0,
            //     'designation' => 'Treasurer',
            //     'status' => 1,
            //     'is_read' => 0,
            // ],
            // [
            //     'name' => 'Rogery Perine',
            //     'email' => 'rogery@mail.com',
            //     'image' => 'Rogery-Perine.jpg',
            //     'password' => bcrypt('12345678'),
            //     'role' => 0,
            //     'designation' => 'Business Manager',
            //     'status' => 1,
            //     'is_read' => 0,
            // ],
            // [
            //     'name' => 'Antonio Darrington',
            //     'email' => 'antonio@mail.com',
            //     'image' => 'Antonio-Darrington.jpg',
            //     'password' => bcrypt('12345678'),
            //     'role' => 0,
            //     'designation' => 'Member At Large',
            //     'status' => 1,
            //     'is_read' => 0,
            // ],
            // [
            //     'name' => 'DeMarcus Smith',
            //     'email' => 'demarcus@mail.com',
            //     'image' => 'DeMarcus-Smith_0.jpg',
            //     'password' => bcrypt('12345678'),
            //     'role' => 0,
            //     'designation' => 'Member At Large',
            //     'status' => 1,
            //     'is_read' => 0,
            // ],
            [
                'name' => 'Anthony Harper',
                'email' => 'anthonyharper@mail.com',
                'image' => 'Anthony-Harper.jpg',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Antonio Darrington',
                'email' => 'antoniodarrington@mail.com',
                'image' => 'Antonio-Darrington.jpg',
                'password' => bcrypt('12345678'),
                'role' => 1,
                'designation' => 'Member At Large',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Carl Sykes',
                'email' => 'carlsykes@mail.com',
                'image' => null,
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Cartez Horton',
                'email' => 'cartezhorton@mail.com',
                'image' => 'Cartez-Horton.jpg',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Charles James',
                'email' => 'charlesjames@mail.com',
                'image' => null,
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Claude Bumpers',
                'email' => 'claudebumpers@mail.com',
                'image' => null,
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Darren Smith',
                'email' => 'darrensmith@mail.com',
                'image' => 'Darren-Smith.jpg',
                'password' => bcrypt('12345678'),
                'role' => 1,
                'designation' => 'Treasurer',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'DeJuan Kidd',
                'email' => 'dejuankidd@mail.com',
                'image' => 'DeJuan-Kidd_0.jpg',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'DeMarcus Smith',
                'email' => 'demarcussmith@mail.com',
                'image' => 'DeMarcus-Smith_0.jpg',
                'password' => bcrypt('12345678'),
                'role' => 1,
                'designation' => 'Member At Large',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Edward Franklin',
                'email' => 'edwardfranklin@mail.com',
                'image' => 'Edward-Franklin.jpg',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Edward Sanderson',
                'email' => 'edwardsanderson@mail.com',
                'image' => 'Ed-Sanderson.jpg',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Edward Thomas',
                'email' => 'edwardthomas@mail.com',
                'image' => 'Edward-Thomas.jpg',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Gabriel Peck',
                'email' => 'gabrielpeck@mail.com',
                'image' => 'Gabriel-Peck.JPG',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Garrard Green',
                'email' => 'garrardgreen@mail.com',
                'image' => 'Garrard-Green.JPG',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Hubert Campbell',
                'email' => 'hubertcampbell@mail.com',
                'image' => 'Hubert-Campbell.JPG',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'James Hunter',
                'email' => 'jameshunter@mail.com',
                'image' => null,
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'James Smith',
                'email' => 'jamessmith@mail.com',
                'image' => 'James-Smith.jpg',
                'password' => bcrypt('12345678'),
                'role' => 1,
                'designation' => 'Financial Secretary',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'James Watson',
                'email' => 'jameswatson@mail.com',
                'image' => 'James-Watson.jpg',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Jason Hackworth',
                'email' => 'jasonhackworth@gmail.com',
                'image' => null,
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Joseph Dennis Jr.',
                'email' => 'josephdennisjr@gmail.com',
                'image' => 'Joseph-Dennis-Jr_0.JPG',
                'password' => bcrypt('12345678'),
                'role' => 1,
                'designation' => 'Vice President',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            // [
            //     'name' => 'Joseph Dennis Sr.',
            //     'email' => 'josephdennissr@gmail.com',
            //     'image' => null,
            //     'password' => bcrypt('12345678'),
            //     'role' => 0,
            //     'designation' => 'Member',
            //     'status' => 1,
            //     'is_read' => 0,
            // ],
            [
                'name' => 'Kenny Holder',
                'email' => 'kennyholder@mail.com',
                'image' => null,
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Leonard Stewart',
                'email' => 'leonardstewart@mail.com',
                'image' => 'Leonard-stewart.JPG',
                'password' => bcrypt('12345678'),
                'role' => 1,
                'designation' => 'President',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Lionel Smith',
                'email' => 'lionelsmith@mail.com',
                'image' => 'Lionel-Smith.JPG',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Lorenzo McKee',
                'email' => 'lorenzomckee@mail.com',
                'image' => 'Lorenzo-McKee.JPG',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Maurice Davis',
                'email' => 'mauricedavis@mail.com',
                'image' => null,
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Maurice Holt',
                'email' => 'mauriceholt@mail.com',
                'image' => 'Maurice-Holt.JPG',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Reginald Crenshaw',
                'email' => 'reginaldcrenshaw@mail.com',
                'image' => 'Reginald-Crenshaw.JPG',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Robert Bettis',
                'email' => 'robertbettis@mail.com',
                'image' => 'Robert-Bettis.jpg',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Robert Moore',
                'email' => 'robertmoore@mail.com',
                'image' => 'Robert-Moore.jpg',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Rogery Perine',
                'email' => 'rogeryperine@mail.com',
                'image' => 'Rogery-Perine.jpg',
                'password' => bcrypt('12345678'),
                'role' => 1,
                'designation' => 'Business Manager',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Stephen Maynard',
                'email' => 'stephenmaynard@mail.com',
                'image' => 'Stephen-Maynard.jpg',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Terrell Washington',
                'email' => 'terrellwashington@mail.com',
                'image' => null,
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Terry Foxx',
                'email' => 'terryfoxx@mail.com',
                'image' => null,
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Tommie Perine',
                'email' => 'tommieperine@mail.com',
                'image' => 'James-Watson.jpg',
                'password' => bcrypt('12345678'),
                'role' => 0,
                'designation' => 'Member',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Tyrone Wiley',
                'email' => 'tyronewiley@mail.com',
                'image' => 'Tyrone-Wiley_0.JPG',
                'password' => bcrypt('12345678'),
                'role' => 1,
                'designation' => 'Recording Secretary',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
            [
                'name' => 'Xavier Poellnitz',
                'email' => 'xavierpoellnitz@mail.com',
                'image' => 'Xavier-Poellnitz.jpg',
                'password' => bcrypt('12345678'),
                'role' => 1,
                'designation' => 'Corresponding Secretary',
                'balance' => 100,
                'status' => 1,
                'is_read' => 0,
            ],
        ];

        User::insert($users);
    }
}
